/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemadragon;

import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Experto");
        setBackground(new java.awt.Color(255, 51, 0));
        setIconImages(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Sistema Experto para Adivinar personajes de");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dragonlogo.png"))); // NOI18N

        jLabel3.setText("Elaboró");

        jLabel4.setText("Erick Jovani Hernández Hernández");

        jLabel5.setText("Daniel Alejandro Rodríguez Resendiz");

        jButton1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jButton1.setText("INICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5))
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(97, 97, 97)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String resTemp = "";
        MotorInferencia x = new MotorInferencia();
        String[] carreras = {
            "Hombre",
            "Mujer"
        };
        String resp = (String) JOptionPane.showInputDialog(null, "El personaje es hombre o mujer??", "Pregunta",
                JOptionPane.DEFAULT_OPTION, null, carreras, carreras[0]);
        x.sacaGenero(resp);
        if (resp.equals("Mujer")) {
            int res = JOptionPane.showConfirmDialog(null, "¿Es humana?", "Pregunta",
                    JOptionPane.YES_NO_OPTION);
            if (res == 0) {
                resp = "Si";
            } else {
                resp = "No";
            }
            x.sacaHumano(resp);
            if (resp.equals("Si")) {
                res = JOptionPane.showConfirmDialog(null, "¿Su pareja es Sayan?", "Pregunta",
                        JOptionPane.YES_NO_OPTION);
                if (res == 0) {
                    resp = "Si";
                } else {
                    resp = "No";
                }
                x.sacaPareja(resp);
                if (res == 1) {
                    JOptionPane.showMessageDialog(null, x.getResultado());
                } else {
                    res = JOptionPane.showConfirmDialog(null, "¿Tiene Cabello Obscuro?", "Pregunta",
                            JOptionPane.YES_NO_OPTION);
                    if (res == 0) {
                        resp = "Si";
                    } else {
                        resp = "No";
                        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bulma.jpg")));
                    }
                    x.sacaCabelloF(resp);
                    if (res == 1) {
                        JOptionPane.showMessageDialog(null, x.getResultado());
                    } else {
                        res = JOptionPane.showConfirmDialog(null, "¿Su personaje vuela?", "Pregunta",
                                JOptionPane.YES_NO_OPTION);
                        if (res == 0) {
                            resp = "Si";
                            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/videl.jpg")));
                        } else {
                            resp = "No";
                            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/milk.jpg")));
                        }
                        x.sacaVuela(resp);
                        JOptionPane.showMessageDialog(null, x.getResultado());
                    }
                }
            } else {
                res = JOptionPane.showConfirmDialog(null, "¿Su personaje es rubia?", "Pregunta",
                        JOptionPane.YES_NO_OPTION);
                if (res == 0) {
                    resp = "Si";
                    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/no18.jpg")));
                } else {
                    resp = "No";
                    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pan.png")));
                }
                x.sacaRubia(resp);
                JOptionPane.showMessageDialog(null, x.getResultado());
            }
        } else {
            System.out.println(x.getResultado());
            int res = JOptionPane.showConfirmDialog(null, "¿Tiene Cabello?", "Pregunta",
                    JOptionPane.YES_NO_OPTION);
            if (res == 0) {
                resp = "Si";
                
            } else {
                resp = "No";
                
            }
            x.sacaCabello(resp);
            System.out.println(x.getResultado());
            if (res == 1) {
                res = JOptionPane.showConfirmDialog(null, "¿Es Humano?", "Pregunta",
                        JOptionPane.YES_NO_OPTION);
                if (res == 0) {
                    resp = "Si";
                } else {
                    resp = "No";
                }
                x.sacaHumanoH(resp);
                System.out.println(x.getResultado());
                if (res == 0) {
                    res = JOptionPane.showConfirmDialog(null, "¿Es Mejor amigo de Goku?", "Pregunta",
                            JOptionPane.YES_NO_OPTION);
                    if (res == 0) {
                        resp = "Si";
                        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Krillin.png")));
                    } else {
                        resp = "No";
                    }
                    x.sacaMejorAmigo(resp);
                    System.out.println(x.getResultado());
                    if (res == 0) {
                        JOptionPane.showMessageDialog(null, x.getResultado());
                        System.out.println(x.getResultado());
                    } else {
                        res = JOptionPane.showConfirmDialog(null, "¿Es Pequeño?", "Pregunta",
                                JOptionPane.YES_NO_OPTION);
                        if (res == 0) {
                            resp = "Si";
                            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chaos.png")));
                        } else {
                            resp = "No";
                        }
                        x.sacaPequenio(resp);
                        if (res == 0) {
                            JOptionPane.showMessageDialog(null, x.getResultado());
                        } else {
                            res = JOptionPane.showConfirmDialog(null, "¿Es Viejo?", "Pregunta",
                                    JOptionPane.YES_NO_OPTION);
                            if (res == 0) {
                                resp = "Si";
                                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/roshi.png")));

                            } else {
                                resp = "No";                                 
                                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tenshinhan.png")));
                            }
                            x.sacaViejoP(resp);
                            JOptionPane.showMessageDialog(null, x.getResultado());
                        }
                    }
                } else {
                    //maestro
                    res = JOptionPane.showConfirmDialog(null, "¿Fue Maestro de alguien?", "Pregunta",
                            JOptionPane.YES_NO_OPTION);
                    if (res == 0) {
                        resp = "Si";
                    } else {
                        resp = "No";
                    }
                    x.sacaMaestro(resp);
                    if (res == 0) {
                        res = JOptionPane.showConfirmDialog(null, "¿Es Viejo?", "Pregunta",
                                JOptionPane.YES_NO_OPTION);
                        if (res == 0) {
                            resp = "Si";
                            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kami.png")));
                        } else {
                            resp = "No";
                            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/picollo.png")));
                        }
                        x.sacaViejo(resp);
                        JOptionPane.showMessageDialog(null, x.getResultado());
                    } else {
                        //villano
                        res = JOptionPane.showConfirmDialog(null, "¿Es un villano?", "Pregunta",
                                JOptionPane.YES_NO_OPTION);
                        if (res == 0) {
                            resp = "Si";
                        } else {
                            resp = "No";
                        }
                        x.sacaVillano(resp);
                        if (res == 0) {
                            res = JOptionPane.showConfirmDialog(null, "¿Lo vencio Goku?", "Pregunta",
                                    JOptionPane.YES_NO_OPTION);
                            if (res == 0) {
                                resp = "Si";
                            } else {
                                resp = "No";
                                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cell.png")));
                            }
                            x.sacaVencio(resp);
                            if (res == 1) {
                                JOptionPane.showMessageDialog(null, x.getResultado());
                            } else {
                                res = JOptionPane.showConfirmDialog(null, "¿Considerado Emperador del Espacio?", "Pregunta",
                                        JOptionPane.YES_NO_OPTION);
                                if (res == 0) {
                                    resp = "Si";
                                    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frezzer.png")));
                                } else {
                                    resp = "No";
                                }
                                x.sacaEmperador(resp);
                                if (res == 0) {
                                    JOptionPane.showMessageDialog(null, x.getResultado());
                                } else {
                                    res = JOptionPane.showConfirmDialog(null, "¿Se regenera?", "Pregunta",
                                            JOptionPane.YES_NO_OPTION);
                                    if (res == 0) {
                                        resp = "Si";
                                        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boo.png")));
                                    } else {
                                        resp = "No";
                                        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nappa.png")));
                                    }
                                    x.sacaRegenera(resp);
                                    JOptionPane.showMessageDialog(null, x.getResultado());
                                }
                            }
                        } else {
                            //animal
                            res = JOptionPane.showConfirmDialog(null, "¿Es un animal?", "Pregunta",
                                    JOptionPane.YES_NO_OPTION);
                            if (res == 0) {
                                resp = "Si";
                            } else {
                                resp = "No";
                                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MrPopo.png")));
                            }
                            x.sacaAnimal(resp);
                            if (res == 1) {
                                JOptionPane.showMessageDialog(null, x.getResultado());
                            } else {
                                res = JOptionPane.showConfirmDialog(null, "¿Se puede transformar?", "Pregunta",
                                        JOptionPane.YES_NO_OPTION);
                                if (res == 0) {
                                    resp = "Si";
                                    
                                } else {
                                    resp = "No";
                                    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ShenLong.png")));
                                    
                                }
                                x.sacaTransforma(resp);
                                if (res == 1) {
                                    JOptionPane.showMessageDialog(null, x.getResultado());
                                } else {
                                    res = JOptionPane.showConfirmDialog(null, "¿Puede volar?", "Pregunta",
                                            JOptionPane.YES_NO_OPTION);
                                    if (res == 0) {
                                        resp = "Si";
                                        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/puar.jpg")));
                                    } else {
                                        resp = "No";
                                        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ulon.png")));
                                    }
                                    x.sacaVuelaH(resp);
                                    JOptionPane.showMessageDialog(null, x.getResultado());

                                }
                            }
                        }
                    }
                }
            } else {
                res = JOptionPane.showConfirmDialog(null, "¿Es un Sayayin?", "Pregunta",
                        JOptionPane.YES_NO_OPTION);
                if (res == 0) {
                    resp = "Si";
                } else {
                    resp = "No";
                }
                x.sacaSayan(resp);
                if (res == 1) {
                    res = JOptionPane.showConfirmDialog(null, "¿Es un Humano?", "Pregunta",
                            JOptionPane.YES_NO_OPTION);
                    if (res == 0) {
                        resp = "Si";
                    } else {
                        resp = "No";
                    }
                    x.sacaHumanoHC(resp);
                    if (res == 0) {
                        res = JOptionPane.showConfirmDialog(null, "¿Ha muerto alguna vez?", "Pregunta",
                                JOptionPane.YES_NO_OPTION);
                        if (res == 0) {
                            resp = "Si";
                            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/yamcha.png")));
                        } else {
                            resp = "No";
                            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/satan.jpg")));
                        }
                        x.sacaMuerto(resp);
                        JOptionPane.showMessageDialog(null, x.getResultado());
                    } else {
                        res = JOptionPane.showConfirmDialog(null, "¿Tiene Hermana?", "Pregunta",
                                JOptionPane.YES_NO_OPTION);
                        if (res == 0) {
                            resp = "Si";
                            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/17.png")));
                        } else {
                            resp = "No";
                            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/no16.jpg")));
                        }
                        x.sacaHermanos(resp);
                        JOptionPane.showMessageDialog(null, x.getResultado());
                    }
                } else {
                    //Raza pura
                    res = JOptionPane.showConfirmDialog(null, "¿Es un Sayayin de Raza Pura?", "Pregunta",
                            JOptionPane.YES_NO_OPTION);
                    if (res == 0) {
                        resp = "Si";
                    } else {
                        resp = "No";
                    }
                    x.sacaRaza(resp);
                    if (res == 1) {
                        res = JOptionPane.showConfirmDialog(null, "¿Derrotó a Cell Perfecto?", "Pregunta",
                                JOptionPane.YES_NO_OPTION);
                        if (res == 0) {
                            resp = "Si";
                            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gohan.png")));
                        } else {
                            resp = "No";
                        }
                        x.sacaDerrotaCell(resp);
                        if (res == 0) {
                            JOptionPane.showMessageDialog(null, x.getResultado());
                        } else {
                            res = JOptionPane.showConfirmDialog(null, "¿Tiene el Cabello Oscuro?", "Pregunta",
                                    JOptionPane.YES_NO_OPTION);
                            if (res == 0) {
                                resp = "Si";
                            } else {
                                resp = "No";
                                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Trunks.png")));
                            }
                            x.sacaCabelloOscuro(resp);
                            if (res == 1) {
                                JOptionPane.showMessageDialog(null, x.getResultado());
                            } else {
                                res = JOptionPane.showConfirmDialog(null, "¿Es el resultado de la fusion?", "Pregunta",
                                        JOptionPane.YES_NO_OPTION);
                                if (res == 0) {
                                    resp = "Si";
                                    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gotens.jpg")));
                                } else {
                                    resp = "No";
                                    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/goten.png")));
                                }
                                x.sacaFusionNoPura(resp);
                                JOptionPane.showMessageDialog(null, x.getResultado());
                            }
                        }
                    } else {
                        //Raza pura si
                        res = JOptionPane.showConfirmDialog(null, "¿Puede Transformarse en Super Sayayin?", "Pregunta",
                                JOptionPane.YES_NO_OPTION);
                        if (res == 0) {
                            resp = "Si";
                        } else {
                            resp = "No";
                        }
                        x.sacaSuperSayan(resp);
                        if (res == 1) {
                            res = JOptionPane.showConfirmDialog(null, "¿Lucho contra frezzer?", "Pregunta",
                                    JOptionPane.YES_NO_OPTION);
                            if (res == 0) {
                                resp = "Si";
                                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bardock.png")));
                            } else {
                                resp = "No";
                                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Raditz.png")));
                            }
                            x.sacaLuchaFrezeer(resp);
                            JOptionPane.showMessageDialog(null, x.getResultado());
                        } else {
                            //Si super sayan
                            res = JOptionPane.showConfirmDialog(null, "¿Es Resultado de la fusión?", "Pregunta",
                                    JOptionPane.YES_NO_OPTION);
                            if (res == 0) {
                                resp = "Si";
                            } else {
                                resp = "No";
                            }
                            x.sacaFusionPura(resp);
                            if (res == 0) {
                                res = JOptionPane.showConfirmDialog(null, "¿Fusión con arsillos Pottara?", "Pregunta",
                                        JOptionPane.YES_NO_OPTION);
                                if (res == 0) {
                                    resp = "Si";
                                    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vegetto.jpg")));
                                } else {
                                    resp = "No";
                                    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Gogeta.jpg")));
                                }
                                x.sacaAretes(resp);
                                JOptionPane.showMessageDialog(null, x.getResultado());
                            } else {
                                res = JOptionPane.showConfirmDialog(null, "¿Es el protagonista?", "Pregunta",
                                        JOptionPane.YES_NO_OPTION);
                                if (res == 0) {
                                    resp = "Si";
                                    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/goku.png")));
                                } else {
                                    resp = "No";
                                }
                                x.sacaRopaNaranja(resp);
                                if (res == 0) {
                                    JOptionPane.showMessageDialog(null, x.getResultado());
                                } else {
                                    res = JOptionPane.showConfirmDialog(null, "¿Usa ropa azul?", "Pregunta",
                                            JOptionPane.YES_NO_OPTION);
                                    if (res == 0) {
                                        resp = "Si";
                                        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vegeta.png")));
                                    } else {
                                        resp = "No";
                                        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/broly.jpg")));
                                    }
                                    x.sacaAmigoGoku(resp);
                                    JOptionPane.showMessageDialog(null, x.getResultado());
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
